name: medical_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^8.1.1
  flutter_bloc: ^9.0.0
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  hugeicons: ^0.0.7
  http: ^1.3.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
